### ISSUE TITLE
"Too many sections big!!" error when loading Mednafen save state

### ISSUE THREAD

**Issue by bbayles** [VGKintsugi/Ghidra-SegaSaturn-Loader#16]
[Here](https://github.com/VGKintsugi/Ghidra-SegaSaturn-Loader/files/15049361/Dungeons.Dragons.Collection.Japan.Disc.1.Tower.of.Doom.458e98aeae4d21ae821a665722d2e5b9.mc0.zip) is a Mednafen save state for Dungeons & Dragons Collection, Disc 1. It fails to load with this error:

```
----- Loading /C:/Games/Mednafen/mcs/Dungeons & Dragons Collection (Japan) (Disc 1) (Tower of Doom).458e98aeae4d21ae821a665722d2e5b9.mc0 -----
Too many sections big!!
java.io.IOException: Too many sections big!!
	at segasaturnloader.SegaSaturnLoader.mssMakeSectionMap(SegaSaturnLoader.java:1325)
	at segasaturnloader.SegaSaturnLoader.loadMednafenSaveState(SegaSaturnLoader.java:1689)
	at segasaturnloader.SegaSaturnLoader.load(SegaSaturnLoader.java:128)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Failed to parse MSS sections!
java.io.IOException: Failed to parse MSS sections!
	at segasaturnloader.SegaSaturnLoader.loadMednafenSaveState(SegaSaturnLoader.java:1692)
	at segasaturnloader.SegaSaturnLoader.load(SegaSaturnLoader.java:128)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:724)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:126)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:368)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Presumably this has something to do with the game's support for the 4MB RAM cartridge. I tried disabling the emulation of that, but got the same error.

Is there anything else I can do to work around this?

Thanks for reading, and for making this loader - I use it all the time!

**Comment by bbayles** [comment]
It turns out that this was caused by emulating a multi-tap. I turned that off and was able to import a save state for this game.

Feel free to close, unless you want to track multi-tap savestate support. Thanks again!

**Comment by VGKintsugi** [comment]
I disabled the Mednafen max sections check temporarily. I also noticed something weird with the BUP loading in the save state, added an exception message. 

Try out the latest release and let me know if you still have problems. I haven't tested much at all.
